### ISSUE TITLE
Manage oauth through backend

### ISSUE THREAD

**Issue by itsravenous** [zooniverse/planetary-response-network#26]
Currently the user signs in on the frontend using zooniverse/panoptes-javascript-client. We've previously discussed several options for how we authorize backend operations with the user's account, rather than a generic account for all operations. The main two options we've discussed are:

1) Continue making oauth calls to Panoptes from the frontend, and pass the obtained access token up to the backend to use.
2) Make oauth calls from the backend to Panoptes using authorization code flow. Store auth token in the user's session and proxy any Panoptes API requests the frontend needs to make (projects, subject sets) through the backend

Re 1) I'm not convinced that an authentication token alone would allow us to determine to which user the token belongs.

2) seems like a better option, but I can't seem to get authorization code flow working with Panoptes. As  I understand it, the following doorkeeper url should display an auth code, but it instead gives a 422 Unprocessable Entity: https://panoptes-staging.zooniverse.org/oauth/authorize?client_id=CLIENT_ID&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=user%20project%20group%20collection%20classification%20subject%20medium%20public
I also followed [this guide](https://github.com/doorkeeper-gem/doorkeeper/wiki/Testing-your-provider-with-OAuth2-gem) to check I was doing things right and arrived at the same URL.

Does anyone know whether Panoptes supports the authorization code flow? I hear @rogerhutchings has been doing something similar with WCG Education?

**Comment by saschaishikawa** [comment]
Bringing @camallen into the conversation.

**Comment by camallen** [comment]
> Re 1) I'm not convinced that an authentication token alone would allow us to determine to which user the token belongs.

hit the `/api/me` route with a valid access token and you'll get the correct user.

Re 2), we use doorkeeper for oauth in panoptes, see https://github.com/doorkeeper-gem/doorkeeper/wiki/authorization-flow it should work but you'll have to be marked as a trusted / secure client [see here](https://github.com/zooniverse/Panoptes/blob/master/lib/gem_ext/doorkeeper/application.rb#L13)

**Comment by itsravenous** [comment]
Thanks for the clarification @camallen! The trusted client thing must be what's missing then - I take it that's just a flag that needs to be set on the app in the db (can't see it in the UI at oauth/applications)
